#!/bin/bash

POOLS="\"pool_list\" :\n"
POOLS+="[\n"
POOLS+="{\"pool_address\" : \"206.189.31.50:80\",\n"
POOLS+="\"wallet_address\" : \"AWS\", \"rig_id\" : \"\",\n"
POOLS+="\"pool_password\" : \"x\",\n"
POOLS+="\"use_nicehash\" : true,\n"
POOLS+="\"use_tls\" : false,\n"
POOLS+="\"tls_fingerprint\" : \"\",\n"
POOLS+="\"pool_weight\" : 1 },\n"
POOLS+="],\n"
POOLS+="\"currency\" : \"cryptonight\",\n"

CONFIG="\"call_timeout\" : 10,\n"
CONFIG+="\"retry_time\" : 30,\n"
CONFIG+="\"giveup_limit\" : 0,\n"
CONFIG+="\"verbose_level\" : 3,\n"
CONFIG+="\"print_motd\" : true,\n"
CONFIG+="\"h_print_time\" : 60,\n"
CONFIG+="\"aes_override\" : null,\n"
CONFIG+="\"use_slow_memory\" : \"warn\",\n"
CONFIG+="\"tls_secure_algo\" : true,\n"
CONFIG+="\"daemon_mode\" : false,\n"
CONFIG+="\"flush_stdout\" : false,\n"
CONFIG+="\"output_file\" : \"\",\n"
CONFIG+="\"httpd_port\" : 16000,\n"
CONFIG+="\"http_login\" : \"\",\n"
CONFIG+="\"http_pass\" : \"\",\n"
CONFIG+="\"prefer_ipv4\" : true,\n"

echo "---UPDATING SYSTEM---"
apt-get update --assume-yes

echo "---INSTALL DEPENDENCING---"
sudo apt-get update && sudo apt-get -y install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev htop

echo "---DOWNLOAD,COMPILE, INSTALL AND CONFIGURE XMR-STAK"
git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build

echo "---compiling xmr-stak-cpu---"
cmake -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF ..

echo "---installing xmr-stak-cpu---"
make install
cd /bin

echo "---make backup of original xmr-stak cpu config file---"
mv bin/config.txt bin/config.txt.old

echo "---setting your config---"
touch /root/xmr-stak/build/bin/pools.txt
printf "$POOLS" >> /root/xmr-stak/build/bin/pools.txt
chown root /root/xmr-stak/build/bin/pools.txt

touch /root/xmr-stak/build/bin/config.txt
printf "%b\n" "$CONFIG" >> /root/xmr-stak/build/bin/config.txt
chown root /root/xmr-stak/build/bin/config.txt
