#!/bin/bash

echo "--MAKE EXECUTABLE CUSTOM FILE---"
echo "cd xmr-stak-cpu/bin/ && ./xmr-stak-cpu" >> miner
chmod +x miner
sysctl -w vm.nr_hugepages=128

echo "---SET EXECUTABLE RUNNING AT REBOOT---"
(crontab -l 2>/dev/null; echo "@reboot screen -d -m /root/miner")| crontab -

echo "---DELETE OLD FILES---"
cd xmr-stak-cpu
shopt -s extglob
rm -rf !(bin)
reboot
