#!/bin/bash

POOLS="\"pool_list\" :\n"
POOLS+="[\n"
POOLS+="{\"pool_address\" : \"206.189.31.50:80\",\n"
POOLS+="\"wallet_address\" : \"AWS\", \"rig_id\" : \"\",\n"
POOLS+="\"pool_password\" : \"x\",\n"
POOLS+="\"use_nicehash\" : true,\n"
POOLS+="\"use_tls\" : false,\n"
POOLS+="\"tls_fingerprint\" : \"\",\n"
POOLS+="\"pool_weight\" : 1 },\n"
POOLS+="],\n"
POOLS+="\"currency\" : \"cryptonight\",\n"

CONFIG="\"call_timeout\" : 10,\n"
CONFIG+="\"retry_time\" : 30,\n"
CONFIG+="\"giveup_limit\" : 0,\n"
CONFIG+="\"verbose_level\" : 3,\n"
CONFIG+="\"print_motd\" : true,\n"
CONFIG+="\"h_print_time\" : 60,\n"
CONFIG+="\"aes_override\" : null,\n"
CONFIG+="\"use_slow_memory\" : \"warn\",\n"
CONFIG+="\"tls_secure_algo\" : true,\n"
CONFIG+="\"daemon_mode\" : false,\n"
CONFIG+="\"flush_stdout\" : false,\n"
CONFIG+="\"output_file\" : \"\",\n"
CONFIG+="\"httpd_port\" : 16000,\n"
CONFIG+="\"http_login\" : \"\",\n"
CONFIG+="\"http_pass\" : \"\",\n"
CONFIG+="\"prefer_ipv4\" : true,\n"

echo "---INSTALL DEPENDENCING---"
sudo apt-get update && sudo apt-get -y install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev htop

echo "---DOWNLOAD,COMPILE, INSTALL AND CONFIGURE XMR-STAK"
git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build
cmake -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF ..
make install
cd /bin

echo "---SETTING YOUR CONFIG---"
touch /root/xmr-stak/build/bin/pools.txt
printf "$POOLS" >> /root/xmr-stak/build/bin/pools.txt
chown root /root/xmr-stak/build/bin/pools.txt

touch /root/xmr-stak/build/bin/config.txt
printf "$CONFIG" >> /root/xmr-stak/build/bin/config.txt
chown root /root/xmr-stak/build/bin/config.txt

echo "--MAKE EXECUTABLE CUSTOM FILE---"
echo "cd /root/xmr-stak/build/bin && ./xmr-stak" >> miner
chown root /root/miner
chmod +x miner

echo "---ADD HUGEPAGES---"
sudo sysctl -w vm.nr_hugepages=128
echo "vm.nr_hugepages = 128" >> /etc/sysctl.conf

echo "---SET EXECUTABLE RUNNING AT REBOOT---"
(crontab -l 2>/dev/null; echo "@reboot screen -d -m /root/miner")| crontab -

echo "---SET AUTO RESTART---"
echo "*/30 *  * * *   root    reboot" >> /etc/crontab

clear
echo "---CONRATULATION, YOUR MINER HAS BEED RUNNING SUCCESSFULLY---"

echo "---YOUR MACHINE WILL BE REBOOT IN---"
sleep 1
echo "---YOUR MACHINE WILL BE REBOOT IN 3...---"
sleep 1
echo "---YOUR MACHINE WILL BE REBOOT IN 3...2...---"
sleep 1
echo "---YOUR MACHINE WILL BE REBOOT IN 3...2...1...---"
sleep 1
echo "---REBOOTING---"
reboot
